export const FALLBACK_MALACHITE_PRODUCTS = [
  {
    id: 'mal-1',
    slug: 'malachite-inlaid-brass-box',
    name: 'Malachite Inlaid Brass Box',
    price: 4999,
    compareAtPrice: 6499,
    category: { name: 'Malachite Decor', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/p2.jpg', isPrimary: true },
      { url: '/images/F/p4.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-2',
    slug: 'malachite-candle-holder',
    name: 'Malachite Candle Holder',
    price: 3499,
    compareAtPrice: 4499,
    category: { name: 'Malachite Decor', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/hold.jpg', isPrimary: true },
      { url: '/images/F/hold1.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-3',
    slug: 'malachite-handcrafted-vase',
    name: 'Malachite Handcrafted Vase',
    price: 5299,
    compareAtPrice: 6799,
    category: { name: 'Malachite Accents', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: false,
    images: [
      { url: '/images/F/product.jpg', isPrimary: true },
      { url: '/images/F/product1.jpg', isSecondary: true },
      { url: '/images/F/product2.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-4',
    slug: 'malachite-gold-table-clock',
    name: 'Malachite & Gold Table Clock',
    price: 5499,
    compareAtPrice: 6999,
    category: { name: 'Malachite Accents', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/s1.jpg', isPrimary: true },
      { url: '/images/F/s2.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-5',
    slug: 'malachite-sculptural-accent',
    name: 'Malachite Sculptural Accent',
    price: 4299,
    compareAtPrice: 5499,
    category: { name: 'Malachite Accents', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/car.jpg', isPrimary: true },
      { url: '/images/F/car2.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-6',
    slug: 'malachite-inlaid-serving-tray',
    name: 'Malachite Inlaid Serving Tray',
    price: 6899,
    compareAtPrice: 8499,
    category: { name: 'Malachite Tableware', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/locate2.jpg', isPrimary: true },
      { url: '/images/F/locate.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-7',
    slug: 'malachite-inlaid-serving-tray-luxe',
    name: 'Malachite Inlaid Serving Tray',
    price: 6899,
    compareAtPrice: 8499,
    category: { name: 'Malachite Tableware', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/shap4.jpg', isPrimary: true },
      { url: '/images/F/shap5.jpg', isSecondary: true },
      { url: '/images/F/shap6.jpg', isSecondary: true },
      { url: '/images/F/shap7.jpg', isSecondary: true },
      { url: '/images/F/shap8.jpg', isSecondary: true },
      { url: '/images/F/shap9.jpg', isSecondary: true },
      { url: '/images/F/shap10.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-8',
    slug: 'malachite-gemstone-bowl',
    name: 'Malachite Gemstone Bowl',
    price: 4599,
    compareAtPrice: 5999,
    category: { name: 'Malachite Decor', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/c1.jpg', isPrimary: true },
      { url: '/images/F/c2.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-9',
    slug: 'hand-carved-malachite-dish',
    name: 'Hand-Carved Malachite Dish',
    price: 3899,
    compareAtPrice: 4899,
    category: { name: 'Malachite Decor', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: false,
    images: [
      { url: '/images/F/b1.jpg', isPrimary: true },
      { url: '/images/F/b2.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-10',
    slug: 'malachite-marble-coaster-set',
    name: 'Malachite & Marble Coasters',
    price: 2499,
    compareAtPrice: 3299,
    category: { name: 'Malachite Tableware', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/box.jpg', isPrimary: true },
      { url: '/images/F/box1.jpg', isSecondary: true },
    ],
  },
  {
    id: 'mal-11',
    slug: 'malachite-brass-jewelry-box',
    name: 'Malachite & Brass Jewelry Box',
    price: 6199,
    compareAtPrice: 7899,
    category: { name: 'Malachite Accents', slug: 'malachite' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/F/ring.jpg', isPrimary: true },
      { url: '/images/F/ring1.jpg', isSecondary: true },
    ],
  },
];

export const FALLBACK_HAND_PAINTED_PRODUCTS = [
  {
    id: 'hp-1',
    slug: 'hand-painted-wooden-wall-art',
    name: 'Hand-Painted Wooden Wall Art',
    price: 3899,
    compareAtPrice: 4999,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h1.jpeg', isPrimary: true },
      { url: '/images/h2.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-2',
    slug: 'hand-painted-terracotta-vase',
    name: 'Hand-Painted Terracotta Vase',
    price: 2799,
    compareAtPrice: 3599,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h3.jpeg', isPrimary: true },
      { url: '/images/h5.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-3',
    slug: 'hand-painted-ceramic-tea-kettle',
    name: 'Hand-Painted Ceramic Tea Kettle',
    price: 4299,
    compareAtPrice: 5499,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: false,
    images: [
      { url: '/images/h6.jpeg', isPrimary: true },
      { url: '/images/h7.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-4',
    slug: 'hand-painted-floral-wooden-tray',
    name: 'Hand-Painted Floral Wooden Tray',
    price: 3199,
    compareAtPrice: 3999,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h8.jpeg', isPrimary: true },
      { url: '/images/h9.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-5',
    slug: 'hand-painted-canvas-tote-bag',
    name: 'Hand-Painted Canvas Tote Bag',
    price: 1999,
    compareAtPrice: 2699,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h10.jpeg', isPrimary: true },
      { url: '/images/h11.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-6',
    slug: 'hand-painted-decorative-brass-plate',
    name: 'Hand-Painted Decorative Brass Plate',
    price: 4899,
    compareAtPrice: 5999,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h12.jpeg', isPrimary: true },
      { url: '/images/h13.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-7',
    slug: 'hand-painted-wooden-accent-box',
    name: 'Hand-Painted Wooden Accent Box',
    price: 2499,
    compareAtPrice: 3299,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: false,
    images: [
      { url: '/images/h14.jpeg', isPrimary: true },
      { url: '/images/h15.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-8',
    slug: 'hand-painted-ceramic-coasters-set',
    name: 'Hand-Painted Ceramic Coasters Set',
    price: 1599,
    compareAtPrice: 2199,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/h16.jpeg', isPrimary: true },
      { url: '/images/h17.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-9',
    slug: 'hand-painted-miniature-art-frame',
    name: 'Hand-Painted Miniature Art Frame',
    price: 2899,
    compareAtPrice: 3699,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: false,
    images: [
      { url: '/images/p1.jpeg', isPrimary: true },
      { url: '/images/p2.jpeg', isSecondary: true },
    ],
  },
  {
    id: 'hp-10',
    slug: 'hand-painted-kalamkari-wall-plate',
    name: 'Hand-Painted Kalamkari Wall Plate',
    price: 3499,
    compareAtPrice: 4299,
    category: { name: 'Hand-Painted Work', slug: 'hand-painted' },
    sale: true,
    featured: true,
    bestSeller: true,
    images: [
      { url: '/images/p3.jpeg', isPrimary: true },
      { url: '/images/h1.jpeg', isSecondary: true },
    ],
  },
];

export const ALL_FALLBACK_PRODUCTS = [
  ...FALLBACK_MALACHITE_PRODUCTS,
  ...FALLBACK_HAND_PAINTED_PRODUCTS,
];
